### ISSUE TITLE
Missing file "bxtexlogo.sty" and wrong pic format(WholeLogo.ai) in my PC

### ISSUE THREAD

**Issue by SavickTso** [Miracle0565/BUCTthesis#2]
[bxtexlogo.zip](https://github.com/Miracle0565/BUCTthesis/files/4581856/bxtexlogo.zip)

I found this missing file online and changed the pic.

**Comment by Miracle0565** [comment]
- The package "bxtexlogo" is contained in TeX Live, or MiKTeX, and i tested the template with TeX Live 2019. So pls tell me your TeX-system. Anyway, this package provides commands to input logos like LaTeX. You may delete the following code in `buctthesis.sty`(line 81):
`\RequirePackage{bxtexlogo}`

- The file `WholeLogo.ai` is created from Adobe Illustrator. If shows wrong in yours, [convert](https://convertio.co/) it to PDF. BTW, how did it wrong? More details pls.

**Comment by SavickTso** [comment]
Sorry for the late response.
I'm using Texmaker in Windows 10, I assume that's the reason why I don't have the "bxtexlogo" file.
The file WholeLogo.ai got a format error, I think it's still the problem of my Tex system.
Thx for your help.

**Comment by Miracle0565** [comment]
Hang on, Texmaker is just a EDITOR ( likes [texstudio](https://www.texstudio.org) and VS code), but not a TeX system(likes [TeX Live](http://tug.org/texlive/) and [CTeX](http://www.ctex.org), so that's NOT the reason why u don't have the file. Please check it up.

**Comment by Miracle0565** [comment]
Hang on, Texmaker is just a EDITOR ( likes [texstudio](https://www.texstudio.org) and VS code), but not a TeX distribution(likes [TeX Live](http://tug.org/texlive/) and [CTeX](http://www.ctex.org), so that's not the reason why u don't have the file. Please check it up.
