### ISSUE TITLE
建议把目录和超链接颜色弄成黑色的

### ISSUE THREAD

**Issue by RonDen** [Miracle0565/BUCTthesis#3]
![image](https://user-images.githubusercontent.com/29707503/81938276-498ba180-9627-11ea-83dc-5d4e205bd8e9.png)
模板中

![image](https://user-images.githubusercontent.com/29707503/81938359-6031f880-9627-11ea-816d-365286cfa6f9.png)
实际要求

![image](https://user-images.githubusercontent.com/29707503/81938403-6f18ab00-9627-11ea-972f-a9c3cdc5027f.png)
样例

**Comment by Miracle0565** [comment]
关于文本颜色在《指南》中有说明。解决方法是载入文档类时添加选项，即
 `\documentclass[TextBlack]{buctthesis}` 
模板默认打开超链接颜色以便于跳转。

另外，请问是否有“样例”文件？
