### ISSUE TITLE
```\LaTeX{}``` was shown different way in Chinese and English version's keyword

### ISSUE THREAD

**Issue by LaoshuBaby** [Miracle0565/BUCTthesis#4]
## Complier Environment

OS： Windows 10

TeX redistribution： TeX Live 2020

version： v0.9.6

## Description

```
The code is the ORIGINAL code in repo at fe0df05
```

The keyword should use 黑体

but in Chinese version it is shown like ```\LaTeX{}```

![图片](https://user-images.githubusercontent.com/42690037/103628743-65f39a00-4f7a-11eb-8fc9-dd2488ab8a45.png)

![图片](https://user-images.githubusercontent.com/42690037/103628814-7c015a80-4f7a-11eb-855c-c368755dd914.png)

should we use universal Linear word "LaTeX" without higher and lower line position, or use ```\LaTeX{}``` in both Chinese version and English version?

**Comment by Miracle0565** [comment]
The command `\LaTeX` will generate uneven characters with the font related to the environment nearby. Actually the font of Chinese Keywords is wrong.

**To fix:**

in `buctthesis.dtx`, line 708:

```TeX
\newcommand{\buct@keywordsfont}{\zihao{4}\heiti}
```

adding the command `\CJKfamily+{}` like:

```TeX
\newcommand{\buct@keywordsfont}{\zihao{4}\heiti\CJKfamily+{}}
```

Then update the `.cls` file and compile:

```
xelatex buctthesis.ins
latexmk
```

Then the font of all characters in both Chinese and English will be set to SimHei.

![图片](https://user-images.githubusercontent.com/53522776/103640809-a3acee80-4f8b-11eb-890d-8162276fa07b.png)

![图片](https://user-images.githubusercontent.com/53522776/103640829-ae678380-4f8b-11eb-8f42-afb17ecbe657.png)


(Really terrible font, personally)

I will update in next version after my exams, thanks.
