### ISSUE TITLE
中英文摘要前应有文章标题

### ISSUE THREAD

**Issue by huangbo2024** [Miracle0565/BUCTthesis#8]
硕士模板：

https://graduate.buct.edu.cn/_upload/article/files/bf/28/d4334dab4084a4e09e3fcd7463c5/ca46b2a2-4ba2-4bf5-a5ac-27463bab2eb6.pdf
（1）论文题目为三号黑体字，可以分成 1 或 2 行居中打印。
（2） 论文题目下空一行居中打印“摘要”二字（小三号黑体），两字间空一格（注：“一格”的标准为一个汉字，以下同）。

另外，overleaf提示编译时间较长

**Comment by Miracle0565** [comment]
## 硕士模板的摘要部分

我核对了一下 [示例文档](https://github.com/the-ccsn/BUCTthesis/tree/master/demo/master-doctor) 和这份《规范》（如果没错的话，链接所给的文档是和 [Readme 中提及的写作规范](https://github.com/the-ccsn/BUCTthesis#%E5%86%99%E4%BD%9C%E8%A7%84%E8%8C%83) 是一样的），貌似没有很明显的差异。因此，烦请**详细**说明问题。

## Overleaf 上编译时间长

编译时间长的问题有很多，所以我们不清楚具体是什么原因造成的。为了帮助排查问题，请：

1. 给出完整或精简的例子，以及 Overleaf 的提示
2. 给出 Overleaf 编译的设置
3. 其他可能有帮助的日志文件等

**Comment by huangbo2024** [comment]
非常感谢，下载后直接修改上传到overleaf，编译结果如图：
![截屏2024-01-18 下午1 56 46](https://github.com/the-ccsn/BUCTthesis/assets/125394145/a857128b-5775-40b8-9d35-3d27376beb09)
![截屏2024-01-18 下午1 57 09](https://github.com/the-ccsn/BUCTthesis/assets/125394145/9466bfb6-9324-43f5-a9a4-40bb770c4ac8)

**Comment by Miracle0565** [comment]
无法复现两张图片中的结果。

但是就文件结构和代码来看，请试着按照以下步骤排查问题：

1. 将 `../demo/master-doctor` 文件夹下的所有文件和文件夹移动到根目录。 [参见 Readme “快速使用”的第 3 条](https://github.com/the-ccsn/BUCTthesis#%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8)

2. 然后，将 `main.tex` 文件中的
  ```TeX
  \makecover
  ```
  删除或注释掉。参见说明文档 [`buctthesis.pdf`](https://github.com/the-ccsn/BUCTthesis/blob/master/buctthesis.pdf) 中的第 3.2 节，对论文封面相关的设置。

如果仍然报错或超时，请按照 `buctthesis.pdf` 文件中的第 2.4 节，精简所有文件，重新编译看看是否有问题。

**Comment by LaoshuBaby** [comment]
确认了一下，都是 “北化大校教发〔2017〕39 号” 文件

![图片](https://github.com/the-ccsn/BUCTthesis/assets/42690037/7e114f24-e0bf-4717-9d72-1fc5a060dbd2)

摘要二字使用小三号黑体可能是确实有问题，因为看起来和上面的"BUCTthesis写作示例文档"一样大了

（源码在哪我还没找，在做了在做了）

Overleaf支持确实就是一塌糊涂，但我编译的时候没遇见这问题只遇见SimSun问题了啊。如果把class、school这些本科的key注释掉，把windows改成fandol，忽略错误（不然会有lipsum没有引用的问题）继续编译，是可以得到结果的

![图片](https://github.com/the-ccsn/BUCTthesis/assets/42690037/f9c1f0c0-307d-4b9d-9e97-e48942147f3d)

我在mycfg中加了一行不然没法编译

![图片](https://github.com/the-ccsn/BUCTthesis/assets/42690037/b73e9835-362b-42b8-84b2-e2dc1870f50a)

（楼上打字比我快一些，此外强烈建议本地texlive）

FYI: 

* 这个issue被记录在 https://t.me/the_ccsn/18424 中，讨论可能会不定期同步到issue（目前还没bot）
* 此外关于研究生使用模板的一些可能遇到的大战 可见 https://github.com/the-ccsn/BUCTthesis/issues/5

**Comment by huangbo2024** [comment]
非常感谢，鉴于问题难以复现
且可能同样会遇见latex转word的问题
还是选择了word从头开始
